# Generated by Django 3.2.9 on 2021-12-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='name_store',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
